import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author amity
 */
public class Home_screen extends javax.swing.JFrame {

    /**
     * Creates new form Home_screen
     */
    public Home_screen() {
        initComponents();
      
     try
     { 
      UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
     }
     catch (Exception e)
     { 
      e.printStackTrace(); 
     }
     
     //color codes start
     
     Color backGround= new Color(74, 35, 90);
     this.getContentPane().setBackground(backGround);
     jPanel1.setBackground(backGround);
     jPanel3.setBackground(backGround);
     confirm_cb.setBackground(backGround);
     confirm_cb.setOpaque(true);
        
     Color heading= new Color(210, 180, 222);
     jLabel1.setForeground(heading);
     
       
     Color font= new Color(155, 89, 182);
     jLabel2.setForeground(font);
     jLabel3.setForeground(font);
     jLabel4.setForeground(font);
     jLabel7.setForeground(font);
     username_tf.setForeground(font);
     account_balance_tf.setForeground(font);
     confirm_cb.setForeground(font);
     amount_tf.setForeground(font);
     you_tf.setForeground(font);
        
     Color tf=new Color(232, 218, 239);
     username_tf.setBackground(tf);
     you_tf.setBackground(tf);
     account_balance_tf.setBackground(tf);
     amount_tf.setBackground(tf);
       
     Color button= new Color(81, 46, 95);
     jButton1.setBackground(button);
     jButton2.setBackground(button);
     jButton3.setBackground(button);
     jButton4.setBackground(button);     
     jButton5.setBackground(button);
     jButton6.setBackground(button);
     
     //color codes end  
    }
     
    public Home_screen(String username1) //using username from login or sign up pages
    { 
     initComponents();
     
     //color codes start
     
     Color backGround= new Color(74, 35, 90);
     this.getContentPane().setBackground(backGround);
     jPanel1.setBackground(backGround);
     jPanel3.setBackground(backGround);
     confirm_cb.setBackground(backGround);
     confirm_cb.setOpaque(true);
        
     Color heading= new Color(210, 180, 222);
     jLabel1.setForeground(heading);
     
       
     Color font= new Color(155, 89, 182);
     jLabel2.setForeground(font);
     jLabel3.setForeground(font);
     jLabel4.setForeground(font);
     jLabel7.setForeground(font);
     username_tf.setForeground(font);
     account_balance_tf.setForeground(font);
     confirm_cb.setForeground(font);
     amount_tf.setForeground(font);
     you_tf.setForeground(font);
        
     Color tf=new Color(232, 218, 239);
     username_tf.setBackground(tf);
     you_tf.setBackground(tf);
     account_balance_tf.setBackground(tf);
     amount_tf.setBackground(tf);
       
     Color button= new Color(81, 46, 95);
     jButton1.setBackground(button);
     jButton2.setBackground(button);
     jButton3.setBackground(button);
     jButton4.setBackground(button);     
     jButton5.setBackground(button);
     jButton6.setBackground(button);
     
     //color codes end
     
     try
     { 
      UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel"); 
     }
     catch (Exception e)
     { 
      e.printStackTrace(); 
     }
     
     try
     { 
      Class.forName("java.sql.DriverManager");
      Connection con;
      con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","amity");
   
      Statement smt=(Statement)con.createStatement();
      String query= "Select * from user_account where username='"+username1+"';";
      ResultSet rs= smt.executeQuery(query);
      
      while(rs.next())
      {
       int amount=rs.getInt("amount");
       you_tf.setText(username1); //set user username in respective tf
       account_balance_tf.setText(""+amount); //set user account balance in respective tf
      }
     }
     catch (Exception e)
     {
      JOptionPane.showMessageDialog(this, e.getMessage());       
     }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        account_balance_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        you_tf = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        username_tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        amount_tf = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        confirm_cb = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Syndicate");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 180, 222), 2), "Your Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(210, 180, 222))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Account Balance in Rupees");

        account_balance_tf.setEditable(false);
        account_balance_tf.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Your Username");

        you_tf.setEditable(false);
        you_tf.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(account_balance_tf)
                    .addComponent(you_tf))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(you_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(account_balance_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(210, 180, 222), 2), "Pay or Send To", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(210, 180, 222))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Username Of The Person You Wish To Send Money");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Enter Amount To Be Paid/Sent (In Rupees)");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Pay/Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        confirm_cb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        confirm_cb.setText("I Have Confirmed The Amount To Be Sent And The Username Mentioned");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(confirm_cb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username_tf)
                            .addComponent(amount_tf))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(username_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(amount_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirm_cb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Add Money");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Change Password");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton6.setText("Veiw Passbook");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("Change Recovery Answers");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//Will Transact Money
        
//Gathering All the info from the form        
String usernamer,usernames;
int amount=Integer.parseInt(amount_tf.getText());
usernamer=username_tf.getText();
usernames=you_tf.getText();
int account=Integer.parseInt(account_balance_tf.getText());

if(usernamer.equals(usernames)) //condition 1: User Not Paying to self
{
 JOptionPane.showMessageDialog(null, "You cannot pay or send to yourself");
}
else //else for condition 1
{
 if(confirm_cb.isSelected()) //condition 2:Confirmation confirmed
 {
  if(account>=amount) //condition 3:User cant exceed his balance
  {
   try
   {
    Class.forName("java.sql.DriverManager");
    Connection con;
    con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/bank","root","amity");
    
    Statement smt1=(Statement)con.createStatement();
    String query1="Insert into transactions(username_sent,username_recieved,amount,trans_date) values('"+usernames+"','"+usernamer+"','"+amount+"',(select curdate()));";
    smt1.executeUpdate(query1);
    
    Statement smt2=(Statement)con.createStatement();
    String query2="Update user_account set amount=amount-"+amount+" where username='"+usernames+"';";
    smt2.executeUpdate(query2);
    
    Statement smt3=(Statement)con.createStatement();
    String query3="Update user_account set amount=amount+"+amount+" where username='"+usernamer+"';";
    smt3.executeUpdate(query3);
    
    amount_tf.setText(null);
    username_tf.setText(null);
    Statement smt=(Statement)con.createStatement();
      String query= "Select * from user_account where username='"+usernames+"';";
      ResultSet rs= smt.executeQuery(query);
      
      while(rs.next())
      {
       int amount2=rs.getInt("amount");
       account_balance_tf.setText(""+amount2); //set user account balance in respective tf
   }
   }
   catch (Exception e)
   {
    String error=(String)e.getMessage();
    if(error.equals("Cannot add or update a child row: a foreign key constraint fails (`bank`.`transactions`, CONSTRAINT `transactions_ibfk_2` FOREIGN KEY (`username_recieved`) REFERENCES `customer_details` (`username`))")) // error condition 1: wrong username input
    {
     JOptionPane.showMessageDialog(null, "Please Enter Correct Username.");
    }
    else //else for error conditions 
    {
     JOptionPane.showMessageDialog(this, e.getMessage());
    }
   }
  }
  else //else for condition 3
  {
   JOptionPane.showMessageDialog(null, "You cannot exceed your account balnce more than your account balance");
   amount_tf.setText("");
  }
 }
 else //else for condition 2
 {
  JOptionPane.showMessageDialog(null, "Please confirm the username and amount entered is correct");
 }
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//Lets user see thier entire record of transactions

String username=you_tf.getText();
new Veiw_passbook(username).setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//Will allow user to addd money to account

JOptionPane.showMessageDialog(null, "We are currently working on this feature, till then you may continue to use the complimantary Rs. 5000 availed to you on the time of creating this account.\n If, however you need to add more money to this account, kindly contact us at syndic@e.com ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//Will log out user

new Old_customer().setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//will open new form to allow user to change password

String username=you_tf.getText(); //collecting information to alow password change
new Change_password(username).setVisible(true); //shows other form
this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//will let user change recovery answers

String username=you_tf.getText();
new Recovery_answers(username).setVisible(true);
this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account_balance_tf;
    private javax.swing.JTextField amount_tf;
    private javax.swing.JCheckBox confirm_cb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField username_tf;
    private javax.swing.JTextField you_tf;
    // End of variables declaration//GEN-END:variables
}
